blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://github.com/ig4e/hayai#issues-feature-requests-and-contributing
    about: For extension-related questions/issues
  - name: 🖥️ Hayai repository
    url: https://github.com/ig4e/hayai
    about: Releases, issues, and project information
